/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: mks_fontHz14.c                                        *
* Font:        ËÎÌו                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Range enabled:        0020 - 007F                                  *
* Range enabled:        00A0 - 00FF                                  *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontmks_fontHz14;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0020[ 16] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0021[ 16] = { /* code 0021, EXCLAMATION MARK */
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0022[ 16] = { /* code 0022, QUOTATION MARK */
  ________,
  ___X__X_,
  __XX_XX_,
  __X__X__,
  _X__X___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0023[ 16] = { /* code 0023, NUMBER SIGN */
  ________,
  ________,
  ________,
  __X__X__,
  __X__X__,
  __X__X__,
  XXXXXXX_,
  _X__X___,
  _X__X___,
  _X__X___,
  XXXXXXX_,
  _X__X___,
  _X__X___,
  _X__X___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0024[ 16] = { /* code 0024, DOLLAR SIGN */
  ________,
  ________,
  ___X____,
  __XXX___,
  _X_X_X__,
  _X_X_X__,
  _X_X____,
  __XX____,
  ___XX___,
  ___X_X__,
  ___X_X__,
  _X_X_X__,
  _X_X_X__,
  __XXX___,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0025[ 16] = { /* code 0025, PERCENT SIGN */
  ________,
  ________,
  ________,
  _X___X__,
  X_X__X__,
  X_X_X___,
  X_X_X___,
  X_X_X___,
  _X_X_X__,
  ___XX_X_,
  __X_X_X_,
  __X_X_X_,
  __X_X_X_,
  _X___X__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0026[ 16] = { /* code 0026, AMPERSAND */
  ________,
  ________,
  ________,
  __XX____,
  _X__X___,
  _X__X___,
  _X__X___,
  _X_X____,
  _XX_XXX_,
  X_X__X__,
  X__X_X__,
  X___X___,
  X___X__X,
  _XXX_XX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0027[ 16] = { /* code 0027, APOSTROPHE */
  ________,
  _XX_____,
  _XX_____,
  __X_____,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0028[ 16] = { /* code 0028, LEFT PARENTHESIS */
  ________,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ____X___,
  ____X___,
  _____X__,
  ______X_,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0029[ 16] = { /* code 0029, RIGHT PARENTHESIS */
  ________,
  _X______,
  __X_____,
  ___X____,
  ___X____,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  __X_____,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_002A[ 16] = { /* code 002A, ASTERISK */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  XX_X_XX_,
  __XXX___,
  __XXX___,
  XX_X_XX_,
  ___X____,
  ___X____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_002B[ 16] = { /* code 002B, PLUS SIGN */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  XXXXXXX_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_002C[ 16] = { /* code 002C, COMMA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  __X_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_002D[ 16] = { /* code 002D, HYPHEN-MINUS */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXXX,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_002E[ 16] = { /* code 002E, FULL STOP */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_002F[ 16] = { /* code 002F, SOLIDUS */
  ________,
  ________,
  _______X,
  ______X_,
  ______X_,
  _____X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0030[ 16] = { /* code 0030, DIGIT ZERO */
  ________,
  ________,
  ________,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0031[ 16] = { /* code 0031, DIGIT ONE */
  ________,
  ________,
  ________,
  ___X____,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0032[ 16] = { /* code 0032, DIGIT TWO */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _____X__,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X____X_,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0033[ 16] = { /* code 0033, DIGIT THREE */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _____X__,
  ___XX___,
  _____X__,
  ______X_,
  ______X_,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0034[ 16] = { /* code 0034, DIGIT FOUR */
  ________,
  ________,
  ________,
  _____X__,
  ____XX__,
  ___X_X__,
  __X__X__,
  __X__X__,
  _X___X__,
  _X___X__,
  _XXXXXX_,
  _____X__,
  _____X__,
  ___XXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0035[ 16] = { /* code 0035, DIGIT FIVE */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X______,
  _X______,
  _X______,
  _X_XX___,
  _XX__X__,
  ______X_,
  ______X_,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0036[ 16] = { /* code 0036, DIGIT SIX */
  ________,
  ________,
  ________,
  ___XXX__,
  __X__X__,
  _X______,
  _X______,
  _X_XX___,
  _XX__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0037[ 16] = { /* code 0037, DIGIT SEVEN */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X___X__,
  _X___X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0038[ 16] = { /* code 0038, DIGIT EIGHT */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0039[ 16] = { /* code 0039, DIGIT NINE */
  ________,
  ________,
  ________,
  ___XX___,
  __X__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__XX_,
  ___XX_X_,
  ______X_,
  ______X_,
  __X__X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_003A[ 16] = { /* code 003A, COLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_003B[ 16] = { /* code 003B, SEMICOLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_003C[ 16] = { /* code 003C, LESS-THAN SIGN */
  ________,
  ________,
  ________,
  ______X_,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  __X_____,
  ___X____,
  ____X___,
  _____X__,
  ______X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_003D[ 16] = { /* code 003D, EQUALS SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  ________,
  ________,
  ________,
  XXXXXXX_,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_003E[ 16] = { /* code 003E, GREATER-THAN SIGN */
  ________,
  ________,
  ________,
  _X______,
  __X_____,
  ___X____,
  ____X___,
  _____X__,
  ______X_,
  _____X__,
  ____X___,
  ___X____,
  __X_____,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_003F[ 16] = { /* code 003F, QUESTION MARK */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _XX___X_,
  ______X_,
  _____X__,
  ____X___,
  ____X___,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0040[ 16] = { /* code 0040, COMMERCIAL AT */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  _X_XX_X_,
  X_X_X_X_,
  X_X_X_X_,
  X_X_X_X_,
  X_X_X_X_,
  X_XX_X__,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0041[ 16] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___XX___,
  __X_X___,
  __X_X___,
  __X__X__,
  __XXXX__,
  _X___X__,
  _X____X_,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0042[ 16] = { /* code 0042, LATIN CAPITAL LETTER B */
  ________,
  ________,
  ________,
  XXXXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  _XXXX___,
  _X___X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0043[ 16] = { /* code 0043, LATIN CAPITAL LETTER C */
  ________,
  ________,
  ________,
  __XXXXX_,
  _X____X_,
  _X____X_,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0044[ 16] = { /* code 0044, LATIN CAPITAL LETTER D */
  ________,
  ________,
  ________,
  XXXXX___,
  _X___X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0045[ 16] = { /* code 0045, LATIN CAPITAL LETTER E */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X____X_,
  _X__X___,
  _X__X___,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X______,
  _X____X_,
  _X____X_,
  XXXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0046[ 16] = { /* code 0046, LATIN CAPITAL LETTER F */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X____X_,
  _X__X___,
  _X__X___,
  _XXXX___,
  _X__X___,
  _X__X___,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0047[ 16] = { /* code 0047, LATIN CAPITAL LETTER G */
  ________,
  ________,
  ________,
  __XXXX__,
  _X___X__,
  _X___X__,
  X_______,
  X_______,
  X_______,
  X___XXX_,
  X____X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0048[ 16] = { /* code 0048, LATIN CAPITAL LETTER H */
  ________,
  ________,
  ________,
  XXX__XXX,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXXX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0049[ 16] = { /* code 0049, LATIN CAPITAL LETTER I */
  ________,
  ________,
  ________,
  _XXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_004A[ 16] = { /* code 004A, LATIN CAPITAL LETTER J */
  ________,
  ________,
  ________,
  __XXXXX_,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  X___X___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_004B[ 16] = { /* code 004B, LATIN CAPITAL LETTER K */
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  _X__X___,
  _X_X____,
  _XXX____,
  _X_X____,
  _X__X___,
  _X__X___,
  _X___X__,
  _X___X__,
  XXX_XXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_004C[ 16] = { /* code 004C, LATIN CAPITAL LETTER L */
  ________,
  ________,
  ________,
  XXX_____,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X____X_,
  XXXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_004D[ 16] = { /* code 004D, LATIN CAPITAL LETTER M */
  ________,
  ________,
  ________,
  XXX_XXX_,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  _X_X_X__,
  XX_X_XX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_004E[ 16] = { /* code 004E, LATIN CAPITAL LETTER N */
  ________,
  ________,
  ________,
  XX___XXX,
  _XX___X_,
  _XX___X_,
  _X_X__X_,
  _X_X__X_,
  _X__X_X_,
  _X__X_X_,
  _X__X_X_,
  _X___XX_,
  _X___XX_,
  XXX___X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_004F[ 16] = { /* code 004F, LATIN CAPITAL LETTER O */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0050[ 16] = { /* code 0050, LATIN CAPITAL LETTER P */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXX__,
  _X______,
  _X______,
  _X______,
  _X______,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0051[ 16] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_____X_,
  X_XX__X_,
  XX__X_X_,
  _X__XX__,
  __XXX___,
  _____XX_,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0052[ 16] = { /* code 0052, LATIN CAPITAL LETTER R */
  ________,
  ________,
  ________,
  XXXXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXX__,
  _X__X___,
  _X__X___,
  _X___X__,
  _X___X__,
  _X____X_,
  XXX___XX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0053[ 16] = { /* code 0053, LATIN CAPITAL LETTER S */
  ________,
  ________,
  ________,
  __XXXXX_,
  _X____X_,
  _X____X_,
  _X______,
  __X_____,
  ___XX___,
  _____X__,
  ______X_,
  _X____X_,
  _X____X_,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0054[ 16] = { /* code 0054, LATIN CAPITAL LETTER T */
  ________,
  ________,
  ________,
  XXXXXXX_,
  X__X__X_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0055[ 16] = { /* code 0055, LATIN CAPITAL LETTER U */
  ________,
  ________,
  ________,
  XXX__XXX,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0056[ 16] = { /* code 0056, LATIN CAPITAL LETTER V */
  ________,
  ________,
  ________,
  XXX__XXX,
  _X____X_,
  _X____X_,
  _X___X__,
  __X__X__,
  __X__X__,
  __X_X___,
  __X_X___,
  ___XX___,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0057[ 16] = { /* code 0057, LATIN CAPITAL LETTER W */
  ________,
  ________,
  ________,
  XX_X_XX_,
  X__X__X_,
  X__X__X_,
  X__X__X_,
  X__X__X_,
  X_X_X_X_,
  X_X_X_X_,
  _XX_XX__,
  _X___X__,
  _X___X__,
  _X___X__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0058[ 16] = { /* code 0058, LATIN CAPITAL LETTER X */
  ________,
  ________,
  ________,
  XXX__XXX,
  _X____X_,
  __X__X__,
  __X__X__,
  ___XX___,
  ___XX___,
  ___XX___,
  __X__X__,
  __X__X__,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0059[ 16] = { /* code 0059, LATIN CAPITAL LETTER Y */
  ________,
  ________,
  ________,
  XXX_XXX_,
  _X___X__,
  _X___X__,
  __X_X___,
  __X_X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_005A[ 16] = { /* code 005A, LATIN CAPITAL LETTER Z */
  ________,
  ________,
  ________,
  _XXXXXX_,
  X____X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  __X_____,
  __X_____,
  _X____X_,
  _X____X_,
  XXXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_005B[ 16] = { /* code 005B, LEFT SQUARE BRACKET */
  ________,
  ___XXXX_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___XXXX_,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_005C[ 16] = { /* code 005C, REVERSE SOLIDUS */
  ________,
  ________,
  _X______,
  _X______,
  __X_____,
  __X_____,
  ___X____,
  ___X____,
  ___X____,
  ____X___,
  ____X___,
  _____X__,
  _____X__,
  _____X__,
  ______X_,
  ______X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_005D[ 16] = { /* code 005D, RIGHT SQUARE BRACKET */
  ________,
  _XXXX___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  _XXXX___,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_005E[ 16] = { /* code 005E, CIRCUMFLEX ACCENT */
  ________,
  ___XXX__,
  __X___X_,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_005F[ 16] = { /* code 005F, LOW LINE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0060[ 16] = { /* code 0060, GRAVE ACCENT */
  ________,
  _XX_____,
  ___X____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0061[ 16] = { /* code 0061, LATIN SMALL LETTER A */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  ___XXXX_,
  __X___X_,
  _X____X_,
  _X____X_,
  __XXXXXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0062[ 16] = { /* code 0062, LATIN SMALL LETTER B */
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X_XX___,
  _XX__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _XX__X__,
  _X_XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0063[ 16] = { /* code 0063, LATIN SMALL LETTER C */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XXX__,
  __X___X_,
  _X______,
  _X______,
  _X______,
  __X___X_,
  ___XXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0064[ 16] = { /* code 0064, LATIN SMALL LETTER D */
  ________,
  ________,
  ________,
  _____XX_,
  ______X_,
  ______X_,
  ______X_,
  ___XXXX_,
  __X___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__XX_,
  ___XX_XX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0065[ 16] = { /* code 0065, LATIN SMALL LETTER E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _XXXXXX_,
  _X______,
  _X______,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0066[ 16] = { /* code 0066, LATIN SMALL LETTER F */
  ________,
  ________,
  ________,
  ____XXXX,
  ___X___X,
  ___X____,
  ___X____,
  _XXXXXX_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0067[ 16] = { /* code 0067, LATIN SMALL LETTER G */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _X___X__,
  _X___X__,
  __XXX___,
  _X______,
  __XXXX__,
  _X____X_,
  _X____X_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0068[ 16] = { /* code 0068, LATIN SMALL LETTER H */
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X_XXX__,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0069[ 16] = { /* code 0069, LATIN SMALL LETTER I */
  ________,
  ________,
  ________,
  __XX____,
  __XX____,
  ________,
  ________,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_006A[ 16] = { /* code 006A, LATIN SMALL LETTER J */
  ________,
  ________,
  ________,
  ____XX__,
  ____XX__,
  ________,
  ________,
  ___XXX__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _X___X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_006B[ 16] = { /* code 006B, LATIN SMALL LETTER K */
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X__XXX_,
  _X__X___,
  _X_X____,
  _XX_X___,
  _X__X___,
  _X___X__,
  XXX_XXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_006C[ 16] = { /* code 006C, LATIN SMALL LETTER L */
  ________,
  ________,
  ________,
  _XXX____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_006D[ 16] = { /* code 006D, LATIN SMALL LETTER M */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  _X__X__X,
  _X__X__X,
  _X__X__X,
  _X__X__X,
  _X__X__X,
  XXX_XX_X,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_006E[ 16] = { /* code 006E, LATIN SMALL LETTER N */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XXX__,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  XXX__XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_006F[ 16] = { /* code 006F, LATIN SMALL LETTER O */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0070[ 16] = { /* code 0070, LATIN SMALL LETTER P */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XX___,
  _XX__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  _XXXX___,
  _X______,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0071[ 16] = { /* code 0071, LATIN SMALL LETTER Q */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XXXX_,
  __X___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __X___X_,
  ___XXXX_,
  ______X_,
  _____XXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0072[ 16] = { /* code 0072, LATIN SMALL LETTER R */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_XXX_,
  __XX__X_,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0073[ 16] = { /* code 0073, LATIN SMALL LETTER S */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _X____X_,
  _X______,
  __XXXX__,
  ______X_,
  _X____X_,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0074[ 16] = { /* code 0074, LATIN SMALL LETTER T */
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  _XXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ____XX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0075[ 16] = { /* code 0075, LATIN SMALL LETTER U */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX___XX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___XX_,
  __XXX_XX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0076[ 16] = { /* code 0076, LATIN SMALL LETTER V */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX__XXX,
  _X____X_,
  __X__X__,
  __X__X__,
  __X_X___,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0077[ 16] = { /* code 0077, LATIN SMALL LETTER W */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_X_XXX,
  X__X__X_,
  X__X__X_,
  X_X_X_X_,
  X_X_X_X_,
  _X___X__,
  _X___X__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0078[ 16] = { /* code 0078, LATIN SMALL LETTER X */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_XXX_,
  __X__X__,
  ___XX___,
  ___XX___,
  ___XX___,
  __X__X__,
  _XXX_XX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_0079[ 16] = { /* code 0079, LATIN SMALL LETTER Y */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX__XXX,
  _X____X_,
  __X__X__,
  __X__X__,
  __X_X___,
  ___XX___,
  ___X____,
  ___X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_007A[ 16] = { /* code 007A, LATIN SMALL LETTER Z */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X___X__,
  ____X___,
  ___X____,
  ___X____,
  __X___X_,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_007B[ 16] = { /* code 007B, LEFT CURLY BRACKET */
  ________,
  ______XX,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  ____X___,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  _____X__,
  ______XX,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_007C[ 16] = { /* code 007C, VERTICAL LINE */
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_007D[ 16] = { /* code 007D, RIGHT CURLY BRACKET */
  ________,
  _XX_____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ____X___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XX_____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_007E[ 16] = { /* code 007E, TILDE */
  __XX____,
  _X__XX__,
  _X____XX,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_007F[ 16] = { /* code 007F, <control> */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

/* Start of unicode area <Latin-1 Supplement> */
GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00A0[ 32] = { /* code 00A0, NO-BREAK SPACE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00A1[ 16] = { /* code 00A1, INVERTED EXCLAMATION MARK */
  ________,
  ________,
  ________,
  ________,
  ________,
  __X_____,
  __X_____,
  ________,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __XX____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00A2[ 16] = { /* code 00A2, CENT SIGN */
  ________,
  ________,
  _____X__,
  _____X__,
  _____X__,
  ___XX___,
  __X_XXX_,
  _X__XXX_,
  _X_X____,
  _X_X____,
  _X_X____,
  __X___X_,
  __XXXX__,
  _X______,
  _X______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00A3[ 16] = { /* code 00A3, POUND SIGN */
  ________,
  ________,
  ________,
  ___XXXX_,
  __X___X_,
  __X_____,
  __X_____,
  __X_____,
  _XXXXX__,
  __X_____,
  __X_____,
  __X____X,
  XXXXX_X_,
  _X__XX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00A4[ 32] = { /* code 00A4, CURRENCY SIGN */
  ________,________,
  _X______,______X_,
  __X_____,_____X__,
  ___X_XXX,XXX_X___,
  ____X___,___X____,
  ___X____,____X___,
  ___X____,____X___,
  ___X____,____X___,
  ___X____,____X___,
  ___X____,____X___,
  ___X____,____X___,
  ____X___,___X____,
  ___X_XXX,XXX_X___,
  __X_____,_____X__,
  _X______,______X_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00A5[ 16] = { /* code 00A5, YEN SIGN */
  ________,
  ________,
  ________,
  _XX___X_,
  __X__X__,
  __X__X__,
  ___X_X__,
  ___XX___,
  XXXXXXXX,
  ____X___,
  XXXXXXXX,
  ____X___,
  ____X___,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00A6[ 16] = { /* code 00A6, BROKEN BAR */
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00A7[ 32] = { /* code 00A7, SECTION SIGN */
  ______XX,X_______,
  _____X__,_X______,
  _____X__,_X______,
  _____X__,________,
  ______X_,________,
  _____X_X,________,
  ____X__X,________,
  ____X___,X_______,
  ____X___,X_______,
  _____X__,X_______,
  _____X_X,________,
  ______X_,________,
  _______X,________,
  ________,X_______,
  ____X___,X_______,
  _____XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00A8[ 32] = { /* code 00A8, DIAERESIS */
  ________,________,
  ________,________,
  ________,________,
  ____XX__,_XX_____,
  ____XX__,_XX_____,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00A9[ 16] = { /* code 00A9, COPYRIGHT SIGN */
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  X_X__XX_,
  XX_____X,
  XX_____X,
  XX_____X,
  X_X__XX_,
  _X_XX_X_,
  __X__X__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00AA[ 16] = { /* code 00AA, FEMININE ORDINAL INDICATOR */
  ________,
  ________,
  XXX_____,
  X__X____,
  XXXX____,
  X__X____,
  XXXX____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00AB[ 16] = { /* code 00AB, LEFT-POINTING DOUBLE ANGLE QUOTATION MARK */
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X___X,
  __X___X_,
  __X__X__,
  _X___X__,
  _X__XX__,
  __X__X__,
  __X___X_,
  ___X__X_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00AC[ 16] = { /* code 00AC, NOT SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXXX,
  _______X,
  _______X,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00AD[ 16] = { /* code 00AD, SOFT HYPHEN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00AE[ 16] = { /* code 00AE, REGISTERED SIGN */
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  X_X_X__X,
  X_X__X_X,
  X_XXX__X,
  X_X_X__X,
  X_X__XX_,
  _X____X_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00AF[ 16] = { /* code 00AF, MACRON */
  XXXXXXXX,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00B0[ 32] = { /* code 00B0, DEGREE SIGN */
  ________,________,
  ___XX___,________,
  __X__X__,________,
  __X__X__,________,
  ___XX___,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00B1[ 32] = { /* code 00B1, PLUS-MINUS SIGN */
  ________,________,
  ________,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  ___XXXXX,XXXX____,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  ________,________,
  ___XXXXX,XXXX____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00B2[ 16] = { /* code 00B2, SUPERSCRIPT TWO */
  ________,
  ________,
  _XXX____,
  X__X____,
  ___X____,
  __X_____,
  _X_X____,
  XXXX____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00B3[ 16] = { /* code 00B3, SUPERSCRIPT THREE */
  ________,
  ________,
  _XXX____,
  ___X____,
  __X_____,
  ___X____,
  ___X____,
  _XX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00B4[ 16] = { /* code 00B4, ACUTE ACCENT */
  ________,
  ________,
  ___X____,
  __X_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00B5[ 16] = { /* code 00B5, MICRO SIGN */
  ________,
  ________,
  ________,
  ________,
  __X___X_,
  __X___X_,
  __X___X_,
  __X___X_,
  __X___X_,
  __X___X_,
  __X_XXXX,
  _X_X____,
  _X______,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00B6[ 16] = { /* code 00B6, PILCROW SIGN */
  ________,
  ________,
  __XXXXX_,
  XXXX_X__,
  XXXX_X__,
  XXXX_X__,
  XXXX_X__,
  _XXX_X__,
  ___X_X__,
  ___X_X__,
  ___X_X__,
  ___X_X__,
  ___X_X__,
  ___X_X__,
  ___X_X__,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00B7[ 32] = { /* code 00B7, MIDDLE DOT */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _______X,X_______,
  _______X,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00B8[ 16] = { /* code 00B8, CEDILLA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __X_____,
  ___X____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00B9[ 16] = { /* code 00B9, SUPERSCRIPT ONE */
  ________,
  ________,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  _XXX____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00BA[ 16] = { /* code 00BA, MASCULINE ORDINAL INDICATOR */
  ________,
  ________,
  _XXX____,
  X__XX___,
  X___X___,
  _X_X____,
  __X_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00BB[ 16] = { /* code 00BB, RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK */
  ________,
  ________,
  ________,
  ________,
  ________,
  X___X___,
  _X__X___,
  __X__X__,
  __X___X_,
  __XX__X_,
  __X__X__,
  _X___X__,
  X___X___,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00BC[ 16] = { /* code 00BC, VULGAR FRACTION ONE QUARTER */
  ________,
  ________,
  _X____X_,
  _X___X__,
  _X___X__,
  _X__X___,
  _X__X___,
  _X_X____,
  ___X__X_,
  __X__XX_,
  __X__XX_,
  __X__XXX,
  _X______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00BD[ 16] = { /* code 00BD, VULGAR FRACTION ONE HALF */
  ________,
  ________,
  _X___X__,
  _X___X__,
  _X___X__,
  _X__X___,
  _X__X___,
  XX_X____,
  ___X_XXX,
  __X____X,
  __X___X_,
  _X___X__,
  _X___XXX,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00BE[ 16] = { /* code 00BE, VULGAR FRACTION THREE QUARTERS */
  ________,
  ________,
  _XX___X_,
  __X__X__,
  _X___X__,
  __X_X___,
  __X_X___,
  _X_X____,
  ___X__X_,
  ___X_XX_,
  __X__XX_,
  __X__XXX,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00BF[ 16] = { /* code 00BF, INVERTED QUESTION MARK */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ________,
  ________,
  ___X____,
  __X_____,
  __X_____,
  _X___X__,
  _X___X__,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00C0[ 16] = { /* code 00C0, LATIN CAPITAL LETTER A WITH GRAVE */
  ___X____,
  ___X____,
  ____X___,
  ___X____,
  ___XX___,
  __X_X___,
  __X_X___,
  __X_X___,
  __X__X__,
  __XXXX__,
  _X___X__,
  _X___X__,
  _X____X_,
  XX___XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00C1[ 16] = { /* code 00C1, LATIN CAPITAL LETTER A WITH ACUTE */
  ____X___,
  ___X____,
  __X_____,
  ___X____,
  ___XX___,
  __X_X___,
  __X_X___,
  __X_X___,
  __X__X__,
  __XXXX__,
  _X___X__,
  _X___X__,
  _X____X_,
  XX___XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00C2[ 16] = { /* code 00C2, LATIN CAPITAL LETTER A WITH CIRCUMFLEX */
  ___XX___,
  __X_X___,
  _____X__,
  ___X____,
  ___XX___,
  __X_X___,
  __X_X___,
  __X_X___,
  __X__X__,
  __XXXX__,
  _X___X__,
  _X___X__,
  _X____X_,
  XX___XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00C3[ 16] = { /* code 00C3, LATIN CAPITAL LETTER A WITH TILDE */
  __XX____,
  ____XX__,
  ________,
  ___X____,
  ___XX___,
  __X_X___,
  __X_X___,
  __X_X___,
  __X__X__,
  __XXXX__,
  _X___X__,
  _X___X__,
  _X____X_,
  XX___XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00C4[ 16] = { /* code 00C4, LATIN CAPITAL LETTER A WITH DIAERESIS */
  __X__X__,
  __XXXX__,
  ________,
  ___X____,
  ___XX___,
  __X_X___,
  __X_X___,
  __X_X___,
  __X__X__,
  __XXXX__,
  _X___X__,
  _X___X__,
  _X____X_,
  XX___XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00C5[ 16] = { /* code 00C5, LATIN CAPITAL LETTER A WITH RING ABOVE */
  ___XX___,
  __X_X___,
  ___XX___,
  ___X____,
  ___XX___,
  __X_X___,
  __X_X___,
  __X_X___,
  __X__X__,
  __XXXX__,
  _X___X__,
  _X___X__,
  _X____X_,
  XX___XXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00C6[ 16] = { /* code 00C6, LATIN CAPITAL LETTER AE */
  ________,
  ________,
  ________,
  ___XXXX_,
  ___XX___,
  __X_X___,
  __X_X___,
  __X_X_X_,
  _X__XXX_,
  _XXXX___,
  _X__X___,
  _X__X___,
  X___X__X,
  XX_XXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00C7[ 16] = { /* code 00C7, LATIN CAPITAL LETTER C WITH CEDILLA */
  ________,
  ________,
  ________,
  ___XXX__,
  __X___XX,
  _X_____X,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _XX____X,
  __XX__X_,
  ____XX__,
  ____X___,
  ____X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00C8[ 16] = { /* code 00C8, LATIN CAPITAL LETTER E WITH GRAVE */
  __XX____,
  ___X____,
  ___X____,
  _XX_XXX_,
  _X____X_,
  _X______,
  _X___X__,
  _X___X__,
  _XXXXX__,
  _X___X__,
  _X______,
  _X______,
  _X____X_,
  XXXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00C9[ 16] = { /* code 00C9, LATIN CAPITAL LETTER E WITH ACUTE */
  ____XX__,
  ____X___,
  ___X____,
  _XX_XXX_,
  _X____X_,
  _X______,
  _X___X__,
  _X___X__,
  _XXXXX__,
  _X___X__,
  _X______,
  _X______,
  _X____X_,
  XXXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00CA[ 16] = { /* code 00CA, LATIN CAPITAL LETTER E WITH CIRCUMFLEX */
  ___XX___,
  __X_X___,
  _X___X__,
  _XXXXXX_,
  _X____X_,
  _X______,
  _X___X__,
  _X___X__,
  _XXXXX__,
  _X___X__,
  _X______,
  _X______,
  _X____X_,
  XXXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00CB[ 16] = { /* code 00CB, LATIN CAPITAL LETTER E WITH DIAERESIS */
  __X_XX__,
  __X_XX__,
  ________,
  _XXXXXX_,
  _X____X_,
  _X______,
  _X___X__,
  _X___X__,
  _XXXXX__,
  _X___X__,
  _X______,
  _X______,
  _X____X_,
  XXXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00CC[ 16] = { /* code 00CC, LATIN CAPITAL LETTER I WITH GRAVE */
  __XX____,
  ___X____,
  ___X____,
  __XXX___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00CD[ 16] = { /* code 00CD, LATIN CAPITAL LETTER I WITH ACUTE */
  ____XX__,
  ____X___,
  ___X____,
  __XXX___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00CE[ 16] = { /* code 00CE, LATIN CAPITAL LETTER I WITH CIRCUMFLEX */
  ___XX___,
  __X_X___,
  ________,
  __XXX___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00CF[ 16] = { /* code 00CF, LATIN CAPITAL LETTER I WITH DIAERESIS */
  __X__X__,
  __X_XX__,
  ________,
  __XXX___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  _XXXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00D0[ 16] = { /* code 00D0, LATIN CAPITAL LETTER ETH */
  ________,
  ________,
  ________,
  __XXXX__,
  __X___X_,
  __X___X_,
  __X____X,
  __X____X,
  __XX___X,
  __X____X,
  __X___XX,
  __X___X_,
  __X__XX_,
  _XXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00D1[ 16] = { /* code 00D1, LATIN CAPITAL LETTER N WITH TILDE */
  __XX____,
  ____XX__,
  ________,
  _X____X_,
  _XX___X_,
  _XX___X_,
  _X_X__X_,
  _X_X__X_,
  _X__X_X_,
  _X__X_X_,
  _X___XX_,
  _X___XX_,
  _X____X_,
  XXX___X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00D2[ 16] = { /* code 00D2, LATIN CAPITAL LETTER O WITH GRAVE */
  __XX____,
  ___X____,
  ___X____,
  __X_XX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00D3[ 16] = { /* code 00D3, LATIN CAPITAL LETTER O WITH ACUTE */
  ____X___,
  ___X____,
  ___X____,
  __X_XX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00D4[ 16] = { /* code 00D4, LATIN CAPITAL LETTER O WITH CIRCUMFLEX */
  ___XX___,
  __X_X___,
  _X___X__,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00D5[ 16] = { /* code 00D5, LATIN CAPITAL LETTER O WITH TILDE */
  __XX____,
  ____XX__,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00D6[ 16] = { /* code 00D6, LATIN CAPITAL LETTER O WITH DIAERESIS */
  __X__X__,
  __X__X__,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __X__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00D7[ 32] = { /* code 00D7, MULTIPLICATION SIGN */
  ________,________,
  ________,________,
  ________,________,
  ___X____,___X____,
  ____X___,__X_____,
  _____X__,_X______,
  ______X_,X_______,
  _______X,________,
  ______X_,X_______,
  _____X__,_X______,
  ____X___,__X_____,
  ___X____,___X____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00D8[ 16] = { /* code 00D8, LATIN CAPITAL LETTER O WITH STROKE */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X___XX_,
  _X__X_X_,
  _X__X_X_,
  _X_X__XX,
  _X_X__X_,
  _XX___X_,
  _XX___X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00D9[ 16] = { /* code 00D9, LATIN CAPITAL LETTER U WITH GRAVE */
  __XX____,
  ___X____,
  ________,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00DA[ 16] = { /* code 00DA, LATIN CAPITAL LETTER U WITH ACUTE */
  ____X___,
  ____X___,
  ___X____,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00DB[ 16] = { /* code 00DB, LATIN CAPITAL LETTER U WITH CIRCUMFLEX */
  ___XX___,
  __X_X___,
  ________,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00DC[ 16] = { /* code 00DC, LATIN CAPITAL LETTER U WITH DIAERESIS */
  __X__X__,
  __X__X__,
  ________,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00DD[ 16] = { /* code 00DD, LATIN CAPITAL LETTER Y WITH ACUTE */
  ____X___,
  ____X___,
  ___X____,
  _XX___X_,
  _X___X__,
  __X__X__,
  __X_X___,
  ___XX___,
  ___XX___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00DE[ 16] = { /* code 00DE, LATIN CAPITAL LETTER THORN */
  ________,
  ________,
  ________,
  _XX_____,
  __X_____,
  __XXX___,
  __X__XX_,
  __X____X,
  __X____X,
  __X____X,
  __X__XX_,
  __XXX___,
  __X_____,
  XXXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00DF[ 16] = { /* code 00DF, LATIN SMALL LETTER SHARP S */
  ________,
  ________,
  ________,
  ___XXX__,
  __X___X_,
  __X___X_,
  __X___X_,
  __X_XX__,
  __X___X_,
  __X___X_,
  __X___X_,
  __X___X_,
  __XXX_X_,
  _XX_XX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00E0[ 16] = { /* code 00E0, LATIN SMALL LETTER A WITH GRAVE */
  _X______,
  __X_____,
  ___X____,
  ________,
  ________,
  _XXX_X__,
  X___XX__,
  X____X__,
  X____X__,
  X____X__,
  X___XX__,
  _XXX_XX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00E1[ 16] = { /* code 00E1, LATIN SMALL LETTER A WITH ACUTE */
  ____X___,
  ___X____,
  __X_____,
  ________,
  ________,
  _XXX_X__,
  X___XX__,
  X____X__,
  X____X__,
  X____X__,
  X___XX__,
  _XXX_XX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00E2[ 16] = { /* code 00E2, LATIN SMALL LETTER A WITH CIRCUMFLEX */
  ________,
  ________,
  __XX____,
  __X_X___,
  _X___X__,
  ________,
  ________,
  _XXXXX__,
  _X___X__,
  ___XXX__,
  _XX__X__,
  _X___X__,
  _X___X_X,
  __XXX_X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00E3[ 16] = { /* code 00E3, LATIN SMALL LETTER A WITH TILDE */
  ________,
  ________,
  __X_____,
  _X_XXX__,
  ________,
  ________,
  ________,
  _XXXXX__,
  _X___X__,
  ___XXX__,
  _XX__X__,
  _X___X__,
  _X___X_X,
  __XXX_X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00E4[ 16] = { /* code 00E4, LATIN SMALL LETTER A WITH DIAERESIS */
  ________,
  ________,
  __X_X___,
  _XX_XX__,
  ________,
  ________,
  ________,
  _XXXXX__,
  _X___X__,
  ___XXX__,
  _XX__X__,
  _X___X__,
  _X___X_X,
  __XXX_X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00E5[ 16] = { /* code 00E5, LATIN SMALL LETTER A WITH RING ABOVE */
  ________,
  ________,
  __XXX___,
  __X_X___,
  ___X____,
  ________,
  ________,
  _XXXXX__,
  _X___X__,
  ___XXX__,
  _XX__X__,
  _X___X__,
  _X___X_X,
  __XXX_X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00E6[ 16] = { /* code 00E6, LATIN SMALL LETTER AE */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX__XX_,
  X__XX__X,
  X__X___X,
  __XXXXXX,
  _X_X____,
  X__X____,
  X__XX__X,
  _XX_XXX_,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00E7[ 16] = { /* code 00E7, LATIN SMALL LETTER C WITH CEDILLA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ___XX___,
  _XX__X__,
  _X___X__,
  _X______,
  _X______,
  _X___X__,
  _X___X__,
  __XXX___,
  __X_____,
  ___X____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00E8[ 16] = { /* code 00E8, LATIN SMALL LETTER E WITH GRAVE */
  _X______,
  __X_____,
  ___X____,
  ________,
  ________,
  __XXX___,
  _X___X__,
  X_____X_,
  XXXXXXX_,
  X_______,
  _X____X_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00E9[ 16] = { /* code 00E9, LATIN SMALL LETTER E WITH ACUTE */
  ____X___,
  ___X____,
  __X_____,
  ________,
  ________,
  __XXX___,
  _X___X__,
  X_____X_,
  XXXXXXX_,
  X_______,
  _X____X_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00EA[ 16] = { /* code 00EA, LATIN SMALL LETTER E WITH CIRCUMFLEX */
  ___X____,
  __X_X___,
  _X___X__,
  ________,
  ________,
  __XXX___,
  _X___X__,
  X_____X_,
  XXXXXXX_,
  X_______,
  _X____X_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00EB[ 16] = { /* code 00EB, LATIN SMALL LETTER E WITH DIAERESIS */
  ________,
  ________,
  ________,
  __X_XX__,
  __X__X__,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _XXXXX__,
  _X______,
  __X___X_,
  ___XXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00EC[ 16] = { /* code 00EC, LATIN SMALL LETTER I WITH GRAVE */
  __X_____,
  ___X____,
  ____X___,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00ED[ 16] = { /* code 00ED, LATIN SMALL LETTER I WITH ACUTE */
  ____X___,
  ___X____,
  __X_____,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00EE[ 16] = { /* code 00EE, LATIN SMALL LETTER I WITH CIRCUMFLEX */
  ________,
  ________,
  ___X____,
  __X_X___,
  _X__X___,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00EF[ 16] = { /* code 00EF, LATIN SMALL LETTER I WITH DIAERESIS */
  ________,
  ________,
  __X_XX__,
  _XX_XX__,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00F0[ 16] = { /* code 00F0, LATIN SMALL LETTER ETH */
  ________,
  ________,
  ________,
  __X__X__,
  ___XX___,
  _XX_X___,
  _____X__,
  __XXXXX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00F1[ 16] = { /* code 00F1, LATIN SMALL LETTER N WITH TILDE */
  ________,
  ________,
  __XX____,
  ___XXX__,
  ________,
  ________,
  ________,
  _XXXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  XXX__XX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00F2[ 16] = { /* code 00F2, LATIN SMALL LETTER O WITH GRAVE */
  __X_____,
  ___X____,
  ____X___,
  ________,
  ________,
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00F3[ 16] = { /* code 00F3, LATIN SMALL LETTER O WITH ACUTE */
  ____X___,
  ___X____,
  __X_____,
  ________,
  ________,
  __XXX___,
  _X___X__,
  X_____X_,
  X_____X_,
  X_____X_,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00F4[ 16] = { /* code 00F4, LATIN SMALL LETTER O WITH CIRCUMFLEX */
  ________,
  ________,
  ___XX___,
  __X_X___,
  _____X__,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00F5[ 16] = { /* code 00F5, LATIN SMALL LETTER O WITH TILDE */
  ________,
  ________,
  __XX____,
  ___XXX__,
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00F6[ 16] = { /* code 00F6, LATIN SMALL LETTER O WITH DIAERESIS */
  ________,
  ________,
  __X_XX__,
  __X_XX__,
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___X__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00F7[ 32] = { /* code 00F7, DIVISION SIGN */
  ________,________,
  ________,________,
  ________,________,
  ______XX,________,
  ______XX,________,
  ________,________,
  ________,________,
  __XXXXXX,XXXX____,
  ________,________,
  ________,________,
  ______XX,________,
  ______XX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00F8[ 16] = { /* code 00F8, LATIN SMALL LETTER O WITH STROKE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _X___XX_,
  _X__X_X_,
  _X_X__X_,
  _XX___X_,
  _X___X__,
  X_XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00F9[ 16] = { /* code 00F9, LATIN SMALL LETTER U WITH GRAVE */
  __X_____,
  ___X____,
  ____X___,
  ________,
  ________,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X___XX__,
  _XXX_XX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00FA[ 16] = { /* code 00FA, LATIN SMALL LETTER U WITH ACUTE */
  ____X___,
  ___X____,
  __X_____,
  ________,
  ________,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X___XX__,
  _XXX_XX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00FB[ 16] = { /* code 00FB, LATIN SMALL LETTER U WITH CIRCUMFLEX */
  ________,
  ________,
  ___XX___,
  __X_X___,
  _X___X__,
  ________,
  ______X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___XX_,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00FC[ 16] = { /* code 00FC, LATIN SMALL LETTER U WITH DIAERESIS */
  ________,
  ________,
  ________,
  ________,
  _X__X___,
  ________,
  X____X__,
  X____X__,
  X____X__,
  X____X__,
  X___XX__,
  _XXX_XX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00FD[ 16] = { /* code 00FD, LATIN SMALL LETTER Y WITH ACUTE */
  ________,
  ________,
  ____XX__,
  ____X___,
  ___X____,
  ________,
  ________,
  __X__X__,
  __X__X__,
  __X__X__,
  ___XX___,
  ___XX___,
  ___X____,
  ___X____,
  ___X____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00FE[ 16] = { /* code 00FE, LATIN SMALL LETTER THORN */
  ________,
  ________,
  XXX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXXXXX_,
  _XX___X_,
  _XX___X_,
  _XX___X_,
  _XX___X_,
  _XX___X_,
  _XXX_X__,
  _XX_X___,
  _XX_____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontmks_fontHz14_00FF[ 16] = { /* code 00FF, LATIN SMALL LETTER Y WITH DIAERESIS */
  ________,
  ________,
  __X__X__,
  __X__X__,
  ________,
  ________,
  ________,
  __X__X__,
  __X__X__,
  __X__X__,
  ___XX___,
  ___XX___,
  ___X____,
  ___X____,
  ___X____,
  _XX_____};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontmks_fontHz14_CharInfo[192] = {
   {   8,   8,  1, acGUI_Fontmks_fontHz14_0020 } /* code 0020 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0021 } /* code 0021 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0022 } /* code 0022 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0023 } /* code 0023 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0024 } /* code 0024 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0025 } /* code 0025 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0026 } /* code 0026 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0027 } /* code 0027 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0028 } /* code 0028 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0029 } /* code 0029 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_002A } /* code 002A */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_002B } /* code 002B */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_002C } /* code 002C */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_002D } /* code 002D */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_002E } /* code 002E */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_002F } /* code 002F */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0030 } /* code 0030 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0031 } /* code 0031 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0032 } /* code 0032 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0033 } /* code 0033 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0034 } /* code 0034 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0035 } /* code 0035 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0036 } /* code 0036 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0037 } /* code 0037 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0038 } /* code 0038 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0039 } /* code 0039 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_003A } /* code 003A */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_003B } /* code 003B */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_003C } /* code 003C */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_003D } /* code 003D */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_003E } /* code 003E */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_003F } /* code 003F */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0040 } /* code 0040 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0041 } /* code 0041 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0042 } /* code 0042 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0043 } /* code 0043 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0044 } /* code 0044 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0045 } /* code 0045 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0046 } /* code 0046 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0047 } /* code 0047 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0048 } /* code 0048 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0049 } /* code 0049 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_004A } /* code 004A */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_004B } /* code 004B */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_004C } /* code 004C */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_004D } /* code 004D */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_004E } /* code 004E */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_004F } /* code 004F */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0050 } /* code 0050 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0051 } /* code 0051 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0052 } /* code 0052 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0053 } /* code 0053 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0054 } /* code 0054 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0055 } /* code 0055 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0056 } /* code 0056 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0057 } /* code 0057 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0058 } /* code 0058 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0059 } /* code 0059 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_005A } /* code 005A */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_005B } /* code 005B */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_005C } /* code 005C */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_005D } /* code 005D */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_005E } /* code 005E */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_005F } /* code 005F */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0060 } /* code 0060 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0061 } /* code 0061 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0062 } /* code 0062 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0063 } /* code 0063 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0064 } /* code 0064 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0065 } /* code 0065 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0066 } /* code 0066 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0067 } /* code 0067 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0068 } /* code 0068 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0069 } /* code 0069 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_006A } /* code 006A */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_006B } /* code 006B */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_006C } /* code 006C */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_006D } /* code 006D */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_006E } /* code 006E */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_006F } /* code 006F */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0070 } /* code 0070 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0071 } /* code 0071 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0072 } /* code 0072 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0073 } /* code 0073 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0074 } /* code 0074 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0075 } /* code 0075 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0076 } /* code 0076 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0077 } /* code 0077 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0078 } /* code 0078 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_0079 } /* code 0079 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_007A } /* code 007A */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_007B } /* code 007B */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_007C } /* code 007C */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_007D } /* code 007D */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_007E } /* code 007E */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_007F } /* code 007F */
  ,{  16,  16,  2, acGUI_Fontmks_fontHz14_00A0 } /* code 00A0 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00A1 } /* code 00A1 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00A2 } /* code 00A2 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00A3 } /* code 00A3 */
  ,{  16,  16,  2, acGUI_Fontmks_fontHz14_00A4 } /* code 00A4 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00A5 } /* code 00A5 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00A6 } /* code 00A6 */
  ,{  16,  16,  2, acGUI_Fontmks_fontHz14_00A7 } /* code 00A7 */
  ,{  16,  16,  2, acGUI_Fontmks_fontHz14_00A8 } /* code 00A8 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00A9 } /* code 00A9 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00AA } /* code 00AA */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00AB } /* code 00AB */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00AC } /* code 00AC */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00AD } /* code 00AD */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00AE } /* code 00AE */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00AF } /* code 00AF */
  ,{  16,  16,  2, acGUI_Fontmks_fontHz14_00B0 } /* code 00B0 */
  ,{  16,  16,  2, acGUI_Fontmks_fontHz14_00B1 } /* code 00B1 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00B2 } /* code 00B2 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00B3 } /* code 00B3 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00B4 } /* code 00B4 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00B5 } /* code 00B5 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00B6 } /* code 00B6 */
  ,{  16,  16,  2, acGUI_Fontmks_fontHz14_00B7 } /* code 00B7 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00B8 } /* code 00B8 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00B9 } /* code 00B9 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00BA } /* code 00BA */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00BB } /* code 00BB */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00BC } /* code 00BC */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00BD } /* code 00BD */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00BE } /* code 00BE */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00BF } /* code 00BF */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00C0 } /* code 00C0 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00C1 } /* code 00C1 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00C2 } /* code 00C2 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00C3 } /* code 00C3 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00C4 } /* code 00C4 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00C5 } /* code 00C5 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00C6 } /* code 00C6 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00C7 } /* code 00C7 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00C8 } /* code 00C8 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00C9 } /* code 00C9 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00CA } /* code 00CA */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00CB } /* code 00CB */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00CC } /* code 00CC */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00CD } /* code 00CD */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00CE } /* code 00CE */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00CF } /* code 00CF */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00D0 } /* code 00D0 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00D1 } /* code 00D1 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00D2 } /* code 00D2 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00D3 } /* code 00D3 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00D4 } /* code 00D4 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00D5 } /* code 00D5 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00D6 } /* code 00D6 */
  ,{  16,  16,  2, acGUI_Fontmks_fontHz14_00D7 } /* code 00D7 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00D8 } /* code 00D8 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00D9 } /* code 00D9 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00DA } /* code 00DA */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00DB } /* code 00DB */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00DC } /* code 00DC */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00DD } /* code 00DD */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00DE } /* code 00DE */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00DF } /* code 00DF */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00E0 } /* code 00E0 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00E1 } /* code 00E1 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00E2 } /* code 00E2 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00E3 } /* code 00E3 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00E4 } /* code 00E4 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00E5 } /* code 00E5 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00E6 } /* code 00E6 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00E7 } /* code 00E7 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00E8 } /* code 00E8 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00E9 } /* code 00E9 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00EA } /* code 00EA */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00EB } /* code 00EB */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00EC } /* code 00EC */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00ED } /* code 00ED */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00EE } /* code 00EE */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00EF } /* code 00EF */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00F0 } /* code 00F0 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00F1 } /* code 00F1 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00F2 } /* code 00F2 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00F3 } /* code 00F3 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00F4 } /* code 00F4 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00F5 } /* code 00F5 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00F6 } /* code 00F6 */
  ,{  16,  16,  2, acGUI_Fontmks_fontHz14_00F7 } /* code 00F7 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00F8 } /* code 00F8 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00F9 } /* code 00F9 */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00FA } /* code 00FA */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00FB } /* code 00FB */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00FC } /* code 00FC */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00FD } /* code 00FD */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00FE } /* code 00FE */
  ,{   8,   8,  1, acGUI_Fontmks_fontHz14_00FF } /* code 00FF */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontmks_fontHz14_Prop2 = {
   0x00A0 /* first character */
  ,0x00FF /* last character  */
  ,&GUI_Fontmks_fontHz14_CharInfo[ 96] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontmks_fontHz14_Prop1 = {
   0x0020 /* first character */
  ,0x007F /* last character  */
  ,&GUI_Fontmks_fontHz14_CharInfo[  0] /* address of first character */
  ,&GUI_Fontmks_fontHz14_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontmks_fontHz14 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontmks_fontHz14_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

